name: 🐛 Bug Report
description: Report a bug in typstyle
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please help us fix it.
        
        **First**: Test your issue in our [playground](https://typstyle-rs.github.io/typstyle/playground) to verify it's reproducible.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Brief description of the issue
      placeholder: A clear description of what went wrong
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code
      description: Minimal Typst code that reproduces the issue
      placeholder: |
        ```typst
        // Your minimal example here
        ```
      render: typst
    validations:
      required: true

  - type: textarea
    id: playground
    attributes:
      label: Playground link (recommended)
      description: If you tested in the playground, paste the URL here
      placeholder: https://typstyle-rs.github.io/typstyle/playground/#...

  - type: textarea
    id: expected
    attributes:
      label: Expected vs actual
      description: What you expected vs what happened
      placeholder: |
        Expected: code formatted like ...
        Actual: code formatted like ...
