name: 🐛 Bug Report
description: Report a bug in typstyle
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please help us fix it.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: A clear description of what went wrong
    validations:
      required: true

  - type: textarea
    id: code-or-url
    attributes:
      label: Code or URL
      description: Typst code that causes the issue, or playground/docs URL
      placeholder: |
        ```typst
        // Your Typst code here
        ```

        OR

        URL: https://typstyle-rs.github.io/typstyle/playground/...
      render: typst
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual
      description: What did you expect vs what actually happened?
      placeholder: |
        Expected:
        ```typst
        // What you expected
        ```

        Actual:
        ```typst
        // What actually happened (or error message)
        ```
    validations:
      required: true
