name: 🐛 Bug Report
description: Report a bug in typstyle
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please help us fix it.
        
        **First**: Test your issue in our [playground](https://typstyle-rs.github.io/typstyle/playground) to verify it's reproducible.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Brief description of the issue
      placeholder: A clear description of what went wrong
    validations:
      required: true

  - type: textarea
    id: playground
    attributes:
      label: Playground link
      description: Test your issue in the playground and paste the URL here. https://typstyle-rs.github.io/typstyle/playground
      placeholder: https://typstyle-rs.github.io/typstyle/playground/#...
    validations:
      required: true
