name: ✨ Feature Request
description: Suggest a new feature or enhancement for typstyle
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe what you want typstyle to do
      placeholder: |
        A clear description of the feature or change you'd like to see.

        For formatting examples, show before/after:
        ```typst
        // Current
        let x=1+2

        // Desired
        let x = 1 + 2
        ```
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Brief explanation of why this would be helpful
      placeholder: This would help because...
