name: Benchmark for master
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run benchmark
        run: cargo bench --workspace -- --output-format bencher | tee output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.PAGES_RESULT_REPO_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '400%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@Enter-tainer'
          gh-repository: 'github.com/typstyle-rs/typstyle-bench-results'
