name: Publish Crates to crates.io

on:
  workflow_call:
    inputs:
      dry-run:
        description: "Perform a dry run without actually publishing"
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Perform a dry run without actually publishing"
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  publish-crates:
    name: Publish Rust crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Publish crates (dry-run)
        if: ${{ inputs.dry-run }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p typstyle-core --dry-run
          cargo publish -p typstyle --dry-run

      - name: Publish crates
        if: ${{ !inputs.dry-run }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p typstyle-core
          cargo publish -p typstyle
